# Generated by Django 2.2.4 on 2021-04-28 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='1', max_length=256)),
                ('directory', models.CharField(choices=[('./strategies/three/', 'three'), ('./strategies/one/', 'one'), ('./strategies/two/', 'two'), ('./strategies/five/', 'five')], default=None, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
