# Generated by Django 2.2.4 on 2021-04-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_strategy_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
