# Generated by Django 2.2.4 on 2021-04-28 21:58

import apps.common.model_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='robo', max_length=256)),
                ('exchange_type', apps.common.model_fields.ChoiceCharField(choices=[('bittrex', 'Bittrex'), ('poloniex', 'Poloniex')], default='bittrex', max_length=30)),
                ('apikey', models.CharField(default='', max_length=256)),
                ('testing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PairHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid_outer', models.CharField(default='', max_length=256)),
                ('exchange_type', apps.common.model_fields.ChoiceCharField(choices=[('bittrex', 'Bittrex'), ('poloniex', 'Poloniex')], default='bittrex', max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('high', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('low', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('close', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('quote_volume', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('quote_volume_add', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid_outer', models.CharField(default='', max_length=256)),
                ('exchange_type', apps.common.model_fields.ChoiceCharField(choices=[('bittrex', 'Bittrex'), ('poloniex', 'Poloniex')], default='bittrex', max_length=30)),
                ('testing', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=11, max_digits=18, null=True)),
                ('price_open', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('price_close', models.DecimalField(decimal_places=11, default=0.0, max_digits=18)),
                ('direction', apps.common.model_fields.ChoiceCharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=30)),
                ('pair', models.CharField(default='', max_length=256)),
                ('status', apps.common.model_fields.ChoiceCharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default='Opened', max_length=30)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strategy.Strategy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
