# Generated by Django 2.2.4 on 2021-04-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairhistory',
            name='uuid_outer',
        ),
    ]
