# Generated by Django 2.2.4 on 2021-04-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_pairhistory_uuid_outer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairhistory',
            name='quote_volume_add',
        ),
    ]
