# Generated by Django 2.2.4 on 2021-04-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_pairhistory_quote_volume_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pairhistory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pairhistory',
            name='uuid',
        ),
        migrations.AddField(
            model_name='pairhistory',
            name='pair',
            field=models.CharField(default='', max_length=256),
        ),
    ]
